NOAA-GFDL/FMScoupler

- .travis.yml
- README.md
- simple/flux_exchange.F90
- t/null_model_build.sh
This add a travis CI build and run test using the null model components and the FMS library.
The build in this update uses `mkmf`.
> Add coupler build and null run test 

- .travis.yml
- README.md
- simple/coupler_main.F90
- simple/flux_exchange.F90
- t/null_model_build.sh
Fix a bug in simple coupler that will cause the model to crash if the ice model domain is not symmetric.
> bug fix for simple coupler

- coupler_main.F90
Added error handling for calls to get_cpu_affinity and also set_cpu_affinity (after changes to function in FMS::mpp/affinity.c)
This needs to be merged at the same time as NOAA-GFDL/FMS#63.
> add error handling to affinity sections in coupler_main.F90

- full/coupler_main.F90
- simple/coupler_main.F90
This PR addresses issue  #7.
This PR merge must be coordinated with the fixes to address issues [#96](https://github.com/NOAA-GFDL/FMS/issues/96) and [#112](https://github.com/NOAA-GFDL/FMS/issues/112) in NOAA-GFDL/FMS.
> utilize new affinity placement API from FMS

- full/atmos_ocean_fluxes_calc.f90
Added epsilons to places where a potential div by zero can occur. Fixes #21
> Fix for issue 21.

- CHANGELOG.md
Changes to be tagged for the new release
> 2020.03 release

- simple/coupler_main.F90
Fixes #33 and hopefully compiles! (removed data_override_init for land ug_domain)
> data_override_init in simple coupler, now even simplerer

- full/atmos_ocean_dep_fluxes_calc.f90
- full/atmos_ocean_fluxes_calc.f90
- simple/coupler_main.F90
- simple/flux_exchange.F90
- simple/ice_model.F90
This adds the license header to several files.
> Adds license header to files

- simple/ice_model.F90
this merge simply adds a few test cases to the ice_model.F90 file in the src/coupler/simple directory.  the test cases are fundamentally no different than other standard test cases that have been present for years.
> Aquaplanet extra sst cases

- CHANGELOG.md
Updates changelog for the 2021.02 release
> 2021.02 release changelog

- SHiELD/coupler_main.F90
Add SHiELD's version of coupler_main to repo.
Simple tests have been run with the SHiELD model.
> Add SHiELD main program driver to repo

- CHANGELOG.md
Updates the changelog for the release
> Update changelog for 2022.01

- CHANGELOG.md
Just updates the changelog with the one change for 2022.03
> update change log for 2022.03

- SHiELD/coupler_main.F90
This PR will bring in updates from @linjiongzhou that update the coupler_main for SHiELD.  Updates are meant to optimize the mpp_clock_begin and mpp_clock_end timer.
> Bring in updates from SHiELD

- CHANGELOG.md
Updates the changelog for the 2023.04 release
> Changelog update for 2023.04 release

- .github/workflows/build.yml
Updating the CI Image to a new version (13.2.0).
> Update to CI Image new version

- CHANGELOG.md
just updates the changelog with the patch info
> chore: update changelog for 2023.04 patch

- CHANGELOG.md
- simple/ice_model.F90
Just brings the patch update into the main branch
> merge 2023.04 patch into main

- CHANGELOG.md
> update changelog for 2024.02

- full/coupler_main.F90
Just fixes a overly long line that snuck in after i fixed the linter
> fix line length for linter

- CHANGELOG.md
> changelog update for 2025.02
