full/coupler_main.F90, simple/coupler_main.F90
This addresses #34 by including "gregorian" as a recognized and supported calendar type.
=> Add support for Gregorian calendar

full/atm_land_ice_flux_exchange.F90
Removed archaic calls creating and setting up Ice%ocean_fluxes_top from the
coupler code.  This structure should have always been private to ice models, and
is not even used by any ice models that are still in active development or use,
but until now this wasteful, unused element had to be retained because of these
misplaced calls.  For any older ice models, the fact that the FMS coupler_types
code supports a copy from a 2d coupler type to a 3d coupler type means that this
could be set up inside of the ice model if it is still needed.  In the
MOM6-examples test suite, all answers are bitwise identical with these changes.
=> Remove archaic calls working on Ice%ocean_fluxes_top

simple/coupler_main.F90
Note: This has not been tested as it only really affects the doubly_periodic model.
Fixes #33
=> Updated simple coupler to call data_override_init properly

shared/surface_flux.F90
This implementation allows to use atmospheric data referenced at different heights
(e.g. ERAinterim, ERA5 for which winds are at 10m, temp and humidity at 2m)
It reproduces answers bitwise with the ncar_ocean_fluxes routine if all variables are
referenced at 10 meters.
=> implementation of CORE (Large&Yeager 2004) with multiple heights

simple/coupler_main.F90
Fixes #33 (again) by adding a namelist flag for whether data_override_init should be executed for any component model.
=> Added do_data_override namelist feature to simple coupler

t/null_model_build.sh
This modifies the test script to not perform the model run.  The script will still compile the code to make sure it builds correctly.
=> Compile only test

simple/coupler_main.F90, simple/flux_exchange.F90, simple/ice_model.F90
Requires https://github.com/NOAA-GFDL/FMS/pull/692 to work. 
Requires FMS2_io ascii io: git@github.com:GFDL-Eric/FMS.git ascii_io to work.
This was only tested with a restart run of `c96L33_am4p0_aqua_ctl` so it needs more testing. 
This PR:
1. Changes ice_model.F90 so that it reads the land_mask files and it reads/writes the ice restart with fms2io. 
2. Removes the `native formatted restart file` code
3. Uses fms2_io ascii_read to read to the coupler_restart
4. Uses fotran's `open`, `close', and `write` to write the coupler_restart
5. Clean up the use statements in coupler_main and flux_exchange.
6. Removes the `read_grid_data` and `get_grid_size` subroutines. These are **never** called:
https://github.com/NOAA-GFDL/FMScoupler/blob/b28cedffe039cb5c0e1ecd07d058d14ca4f2599b/simple/ice_model …
=> Implements fms2_io to simple coupler files

full/atm_land_ice_flux_exchange.F90, full/coupler_main.F90, full/flux_exchange.F90
Requires:
1. FMS2_io ascii io: git@github.com:GFDL-Eric/FMS.git ascii_io
2. FMS2_io's version of coupler_types: git@github.com:uramirez8707/FMS.git fms2_io_coupler_types
3. Supergrid creation: git@github.com:uramirez8707/FMS.git supergrid
This PR:
1.  The coupler restart files are now read with fms2_io's [ascii_read](https://github.com/GFDL-Eric/FMS/blob/d61bfa851e476cf5e5aecb647d2c06f0e7ebdd97/fms2_io/fms_io_utils.F90#L461-L468)
2. Ascii writes are now done with fortran's `open`, `close`, and `write`. They are wrapped in an if, so that only the root pe does the io, `newunit` ensures that the unit number is unique for each file. I renamed the variables `unit` because that's already a fortran thing ...
3. The coupler type restarts are now written with fms2_io. 
4. The grid file is now read …
=> Implement fms2_io to full coupler

full/flux_exchange.F90
Fixes #59 
Corrects a `get_variable_size` call to prevent ` FATAL: incorrect size of dim_sizes array.` crashes when running with the SCM.
=> Fixes a get_variable_size call in flux/flux_exchange

CHANGELOG.md
Updates the changelog. Just changes the header that was added with the last patch since its the only update for this release
=> Updates the changelog for 2021.03

README.md
Adds some of the information provided on this site:
https://www.gfdl.noaa.gov/guide-to-grid-coupling-in-fms/
to the README markdown file.
I plan on doing some doxygen updates similar to fms for the coupler soon, so some information may be added later or moved. I also added a link to FRE-NCtools, since I figured that would be more helpful for grid generation.
=> docs: add information from gfdl site to readme

SHiELD/coupler_main.F90, full/coupler_main.F90, simple/coupler_main.F90
Removes grid code and variables from SHiELD/coupler_main and fixes data_override_init
Removes outdated logic in simple/coupler_main for data_override_init parsing
Relies upon [FMS PR #933](https://github.com/NOAA-GFDL/FMS/pull/933)
=> Data override updates and bugfixes

simple/flux_exchange.F90
Fixes failures while running in debug mode with gnu.
Tested with aquaplanet regressions, fixed gnu issues.
=> Add allocations for u_ref and v_ref

full/coupler_main.F90, simple/coupler_main.F90
Updates the constants init routines to use the updated name from https://github.com/NOAA-GFDL/FMS/pull/929
needs this to compile with current FMS main
=> Update constant initialization routine name

full/coupler_main.F90
This sets a large value for omp_set_max_active_levels which should default to the implementation maximum.  This resolves #68
=> Replacing omp_set_nested 

.github/workflows/build.yml, simple/ice_model.F90, t/null_model_build.sh
Changes the script to add an option to copy FMS instead of cloning in order to run in the CI for https://github.com/NOAA-GFDL/FMS/pull/975 , and changes the output so it'll  be displayed on github.
Also makes a few code changes to allow the null model tests to run. 
The ice model would fail from attempting to read without an io domain, so the added code just checks for an associated io domain before it tries to open the ice files.
=> Fixes to run the null model

SHiELD/coupler_main.F90, full/coupler_main.F90, simple/coupler_main.F90
adds ifdefs for io deprecation
tested this with the null model, just pulled https://github.com/NOAA-GFDL/FMS/pull/1064 instead of main for FMS
=> Add ifdefs for fms_io_exit calls

t/null_model_build.sh
the null_model was updated for fms2_io, this just adds a line to the test script to insert a 1,1 layout because it was failing with the default.
=> fix test script for null_ice update

shared/surface_flux.F90
-Closes Issue #81
-Some models were crashing in debug mode due to unitialized variables in the namelist
=> Fix crash due to uninitialized vars in namelist

SHiELD/coupler_main.F90, full/atm_land_ice_flux_exchange.F90, full/atmos_ocean_dep_fluxes_calc.F90, full/atmos_ocean_fluxes_calc.F90, full/coupler_main.F90, full/flux_exchange.F90, full/ice_ocean_flux_exchange.F90, full/land_ice_flux_exchange.F90, shared/surface_flux.F90, simple/coupler_main.F90, simple/flux_exchange.F90, simple/ice_model.F90
This changes all the FMS routine calls, derived types, and modules to be updated with FMS's most up-to-date naming conventions. All FMS references will be denoted with `fms` as a prefix
This PR is dependent on https://github.com/NOAA-GFDL/FMS/pull/1262
=> Changes any FMS routine calls or references to new FMS naming convention

full/coupler_main.F90
In the current form, the coupler does not correctly assign PEs when using a data atmosphere (do_atmos=false) and the combined ice-ocean driver (combined_ice_and_ocean = .true.). In that case, all PEs are atmosphere PEs, ocean PEs, slow-ice PEs, and fast-ice PEs. To address this, new options have been added where the ice PE list is assigned.
The logic where the ice PE list is defined has been changed to use the do_atmos, shared_slow_fast_PEs, and slow_ice_with_ocean options for four cases:
(1) fully coupled configurations that do not use the combined ice-ocean driver,
(2) fully coupled configurations that do use the combined ice-ocean driver, 
(3) data atmosphere configurations that do not use the combined ice-ocean driver, and 
(4) data atmosphere configurations that do use the combined …
=> Changes to allow data atmosphere with the interspersed sea-ice coupling

.github/workflows/build.yml, t/null_model_build.sh
Switches out the container image. Needed two small changes to the test script in order run on the new image.
=> Update CI to use github container registry image

full/atm_land_ice_flux_exchange.F90, shared/surface_flux.F90, simple/flux_exchange.F90
This PR is linked to issue #92. 
A new boundary layer scheme (NCEP TKE-based eddy-diffusivity mass-flux scheme) is being implemented in the prototype-AM5 model, and it requires five additional surface variables (shflx, lhflx, wind, thv_atm, and thv_surf) as inputs. Thus, I would like to add a few lines in the surface coupler (full/atm_land_ice_flux_exchange.F90 and shared/surface_flux.F90) to pass these variables into the atmospheric model. My branch contains the proposed changes, and the model results are unchanged with these changes.
=> Passing additional surface variables into the atmospheric model #92

full/atm_land_ice_flux_exchange.F90, full/land_ice_flux_exchange.F90
Subroutines `fms_xgrid_stock_move` and `fms_xgrid_stock_move_ug` have had their internal variable, `DATA`, changed in the FMS `data` keyword replacement. `DATA` is changed to `stock_data3d`, `stock_data2d`, or `stock_ug_data3d` depending on which variant of the `stock_move` subroutine is used (`stock_move_3d`, `stock_move_2d`, `stock_move_ug_3d`, respectively). When calling these subroutines, the internal variable is referenced accordingly, reflecting the changes in the FMS xgrid_mod.
=> Keyword `DATA` FMS update

full/atm_land_ice_flux_exchange.F90
=> [Draft] Adding comments for documentation

full/coupler_main.F90
Add a diag_send_complete call. This is needed for the new diag manager. It is backwards compatible with the old diag manager.
=> Add a diag_send_complete call

SHiELD/coupler_main.F90
This PR fixes #103 by adding `'GREGORIAN'` as an option in the select case statement for inferring the `calendar_type` in SHiELD's `coupler_main.F90`.  I tested this in a short simulation (including a restart) and things ran without a problem, so this indeed appears as simple as @bensonr suggested.
cc: @lharris4
=> Enable running SHiELD with a Gregorian calendar

SHiELD/coupler_main.F90
Enable fms_data_override_init() to work in nest domains.
=> Enable data override in nest domains for SHiELD coupler 

full/atm_land_ice_flux_exchange.F90, full/flux_exchange.F90
Changed two files, flux_exchange.F90 and atm_land_ice_flux_exchange.F90 to remove unused bug variables from the past.
=> forked version of removal of unused bug variables

simple/ice_model.F90
During the libFMS updates, it seems this line was updated when it shouldn't have been. It should be using the namelist's value rather than pulling in the variable of the same name from amip_interp.
=>  correct sst_anom usage to use nml value

shared/surface_flux.F90, simple/flux_exchange.F90
For the current model setting, the ocean roughness for momentum, heat and moisture is input variables which are calculated based on the atmospheric condition at the previous time step. We add one option to update the ocean roughness by iterating the monin obukhov function so as to obtain concurrent roughness, drag and heat/moisture coefficients.
=> add an option to obtain the cocurrent drag and heat transfer coeffients

SHiELD/coupler_main.F90
Fix a bug where data_override cannot load external sst correctly in the case of SHiELD. It turns out that "mode" needs to be specified when fms data override is initialized. This fix is provided by @lharris4 .
=> Fix a bug where data_override does not work

full/coupler_main.F90
This PR fixes a crash that occurs when do_flux=.F.
Currently `do_flux` is only invoked when calling `coupler_sfc_boundary_layer`.
When do_flux is off, calls to `coupler_flux_down_from_atmos`, `coupler_flux_up_to_atmos` and `coupler_flux_atmos_to_ocean` will cause a code crash since they depend on exchange grid quantities/fluxes allocated and set up by `sfc_boundary_layer`
This has been tested with the new version of SHiELD employing the new coupler.
=> revise do_flux logic

SHiELD/coupler_main.F90
Adding in an `&` where it was missed.  This is needed to compile SHiELD.
Fixes Issue #139
=> Add in missing &

full/atm_land_ice_flux_exchange.F90
Adding ocean temperature and rough heat to `land_ice_atmos_boundary` to used and populated on the exchange grid from ocean variables in `sfc_boundary_layer`, before running the atmos physics for shield coupling.
Contact: Joseph and Kun
=> Add ocean temp and rough heat in for shield coupling

CODE_OF_CONDUCT.md, CODE_STYLE.md, CONTRIBUTING.md, README.md
This PR adds the instructions for contributing to coupler including a contribution guide, a code style guide, and a code of conduct with expected behavior.  There is also a link to the contribution guide at the top of the README so people will see it immediately when they visit the main page of this repo.
=> Adds documents for guidelines on contributing

simple/coupler_main.F90
Just adds a init call so the simple coupler does not error out when the generic exchange module is used in components.
=> Update simple coupler to initialize generic_exchange module
